import type { Metadata } from "next";
import "../globals.css";
import ClientLayout from "@/components/layout/client-layout";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Clark",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider defaultOpen={true}>
      <div className="flex h-screen w-full">
        <AppSidebar />
        <SidebarInset className="flex-1 overflow-hidden">
          <ClientLayout>
            {children}
          </ClientLayout>
        </SidebarInset>
      </div>
    </SidebarProvider>
  );
}
