import type { Metadata } from "next";
import "./globals.css";
// import "github-markdown.css";
import { sfProRounded } from "./fonts";
import { Providers } from "@/components/providers";



export const metadata: Metadata = {
  title: "Clark",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sfProRounded.className} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
